function results = assembleDragResults( ...
    Mach, velocity, dynamicPressure, ...
    skinFriction, waveDrag)
%ASSEMBLEDRAGRESULTS Adds all drag components and creates a results table.

Mach            = Mach(:).';
velocity        = velocity(:).';
dynamicPressure = dynamicPressure(:).';

%% Total drag coefficient

CDtotal = ...
    skinFriction.CD + ...
    waveDrag.CD;

%% Total drag force

totalForce = ...
    skinFriction.force + ...
    waveDrag.force;

%% Store arrays

results.Mach            = Mach;
results.velocity        = velocity;
results.dynamicPressure = dynamicPressure;

results.CD.skinFriction = skinFriction.CD;
results.CD.wave         = waveDrag.CD;
results.CD.total        = CDtotal;

results.force.skinFriction = skinFriction.force;
results.force.wave         = waveDrag.force;
results.force.total        = totalForce;

results.ReynoldsNumber = skinFriction.ReynoldsNumber;
results.Cf             = skinFriction.Cf;
results.waveBlend      = waveDrag.blendFactor;

%% Create results table

results.table = table( ...
    Mach.', ...
    skinFriction.ReynoldsNumber.', ...
    dynamicPressure.', ...
    skinFriction.Cf.', ...
    skinFriction.CD.', ...
    waveDrag.CD.', ...
    CDtotal.', ...
    skinFriction.force.', ...
    waveDrag.force.', ...
    totalForce.', ...
    'VariableNames', { ...
    'Mach', ...
    'ReynoldsNumber', ...
    'DynamicPressure_Pa', ...
    'Cf', ...
    'CD_Friction', ...
    'CD_Wave', ...
    'CD_Total', ...
    'DragFriction_N', ...
    'DragWave_N', ...
    'DragTotal_N'});

end